spring:
  datasource:
    url: jdbc:h2:file:./testdb
    username: sa
    password: asdf
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  sql:
    init:
      mode: always
      encoding: UTF-8

logging.level:
  org.hibernate.SQL: debug